// @vynel/sdk — TypeScript types + runtime client for the Vynel v1 API.
//
// Three artifacts power this package, all regenerated by
// `pnpm api:generate` from the live API's hono-openapi spec:
//   - `../openapi.json`           — the OpenAPI 3.1 document snapshot.
//   - `./generated/api.d.ts`      — typed paths/components/operations.
//   - `./generated/namespaced.ts` — the `client.knowledge.search()`
//     facade, derived from each route's `x-sdk-name`.
//
// The runtime wraps openapi-fetch with the generated `paths` type and
// composes the namespaced facade onto the same instance — one chain,
// no duplication: route → openapi.json → SDK types → fetcher.
//
// Consumers:
//   - `apps/web` — instantiates `createVynelClient(...)` once in
//     `main.ts` and provides it via `app.provide('vynelApi', client)`;
//     composables read it via `useVynelApi()` (`inject`).
//   - Future external SDK consumers — fire when the publishing trigger
//     (`.claude/rules/sdk-mcp.md` "Deferred") fires; same factory.
//
// Phase 1 has no auth — the bearer-token + 401-interceptor middleware
// in letterman's @letterman/sdk client are deliberately omitted here.
// They land alongside the Phase 2 `auth` domain.

import createClient, { type Client } from 'openapi-fetch'

import type { paths } from './generated/api.js'
import { makeNamespaced } from './generated/namespaced.js'

export type * from './generated/api.js'
export { SdkError } from './errors.js'

/**
 * Options for constructing the typed Vynel API client.
 *
 * `baseUrl` is the only required field. In `apps/web` dev, leave it as
 * the empty string — the Vite dev server proxies `/workspaces`,
 * `/users`, ... to the `apps/local-api` process on `http://localhost:18892`.
 * In tests, point it at the test-server URL.
 *
 * Phase 1 has no auth. Phase 2 will widen this with `getAuthToken` +
 * `onUnauthorized` (letterman's pattern in `@letterman/sdk`).
 */
export interface VynelClientOptions {
  baseUrl: string
}

/**
 * Typed Vynel API client. Carries BOTH surfaces on one instance:
 *   - path-keyed — `client.GET('/...')` etc., returns `{ data, error }`.
 *   - namespaced — `client.knowledge.search(...)`, returns the body and
 *     throws `SdkError` on non-2xx.
 * Both are typed against the generated `paths` type.
 */
export type VynelClient = Client<paths> & ReturnType<typeof makeNamespaced>

/**
 * Construct a typed openapi-fetch client against the Vynel API.
 *
 * Single source of truth: the generated `paths` type ultimately
 * derives from `apps/local-api`'s route schemas (which import Zod schemas
 * from `@vynel/contracts`). One chain — no duplication.
 *
 * @example
 * ```ts
 * const vynelApi = createVynelClient({ baseUrl: '' })
 *
 * // path-keyed:
 * const { data, error } = await vynelApi.GET(
 *   '/workspaces/{workspaceId}/knowledge/status',
 *   { params: { path: { workspaceId } } },
 * )
 *
 * // namespaced (throws SdkError on non-2xx):
 * const results = await vynelApi.knowledge.search(workspaceId, { query: 'onboarding' })
 * ```
 */
export function createVynelClient(options: VynelClientOptions): VynelClient {
  const client = createClient<paths>({ baseUrl: options.baseUrl })
  // Compose the two surfaces onto one instance: the path-keyed
  // `client.GET(...)` (returns `{ data, error }`) and the namespaced
  // `client.knowledge.search(...)` (returns the body, throws SdkError).
  // Both share the same fetch + config.
  return Object.assign(client, makeNamespaced(client))
}
