// @vynel/sdk — TypeScript types + runtime client for the Vynel v1 API.
//
// Two artifacts power this package:
//   - `./generated/api.d.ts` — typed paths/components/operations
//     (regenerated by `pnpm api:generate` from the live API's
//     hono-openapi spec).
//   - `../openapi.json`      — the OpenAPI 3.1 document snapshot.
//
// The runtime client wraps openapi-fetch with the generated `paths`
// type — see `.claude/memory/decisions/apps-web-foundation-design.md`
// for the locked architecture (single chain:
// `@vynel/contracts` → API → openapi.json → SDK types → fetcher).
//
// Consumers:
//   - `apps/web` — instantiates `createVynelClient(...)` once in
//     `main.ts` and provides it via `app.provide('vynelApi', client)`;
//     composables read it via `useVynelApi()` (`inject`).
//   - Future external SDK consumers — fire when the publishing trigger
//     (`.claude/rules/sdk-mcp.md` "Deferred") fires; same factory.
//
// Phase 1 has no auth — the bearer-token + 401-interceptor middleware
// in letterman's @letterman/sdk client are deliberately omitted here.
// They land alongside the Phase 2 `auth` domain.

import createClient, { type Client } from 'openapi-fetch'

import type { paths } from './generated/api.js'

export type * from './generated/api.js'

/**
 * Options for constructing the typed Vynel API client.
 *
 * `baseUrl` is the only required field. In `apps/web` dev, leave it as
 * the empty string — the Vite dev server proxies `/workspaces`,
 * `/users`, ... to the `apps/api` process on `http://localhost:8998`.
 * In tests, point it at the test-server URL.
 *
 * Phase 1 has no auth. Phase 2 will widen this with `getAuthToken` +
 * `onUnauthorized` (letterman's pattern in `@letterman/sdk`).
 */
export interface VynelClientOptions {
  baseUrl: string
}

/**
 * Typed Vynel API client. Exposes `GET`, `POST`, `PATCH`, `PUT`,
 * `DELETE` methods keyed against the generated `paths` type — so
 * route + query + body + response are all fully typed.
 */
export type VynelClient = Client<paths>

/**
 * Construct a typed openapi-fetch client against the Vynel API.
 *
 * Single source of truth: the generated `paths` type ultimately
 * derives from `apps/api`'s route schemas (which import Zod schemas
 * from `@vynel/contracts`). One chain — no duplication.
 *
 * @example
 * ```ts
 * const vynelApi = createVynelClient({ baseUrl: '' })
 *
 * const { data, error } = await vynelApi.GET('/workspaces', {
 *   params: { query: { includeArchived: false } },
 * })
 * ```
 */
export function createVynelClient(options: VynelClientOptions): VynelClient {
  return createClient<paths>({ baseUrl: options.baseUrl })
}
