// The catalog's Phosphor components, mapped statically so the bundle only
// carries icons the shelf can actually use. The catalog names are a contracts
// allowlist (`CatalogIconName`) — data-level, so they stay lucide-flavored
// kebab-case even though the components behind them are Phosphor now; adding
// or removing a name in ONE home without the other fails the compile here.
// An iconName outside the map (legacy hub rows) falls back to the monogram.

import type { Component } from "vue";
import {
  PhBookOpen as BookOpen,
  PhBookmarkSimple as Bookmark,
  PhRobot as Bot,
  PhBriefcase as Briefcase,
  PhCalendar as Calendar,
  PhChartBar as ChartBar,
  PhChartPie as ChartPie,
  PhCheckCircle as CircleCheck,
  PhClipboard as Clipboard,
  PhClock as Clock,
  PhCloud as Cloud,
  PhCode as Code,
  PhDatabase as Database,
  PhFileText as FileText,
  PhFilmStrip as Film,
  PhFolder as Folder,
  PhGlobe as Globe,
  PhGraduationCap as GraduationCap,
  PhImage as Image,
  PhTray as Inbox,
  PhKey as Key,
  PhTranslate as Languages,
  PhLayout as LayoutTemplate,
  PhLightbulb as Lightbulb,
  PhLink as Link,
  PhListChecks as ListChecks,
  PhEnvelopeSimple as Mail,
  PhMapTrifold as MapIcon,
  PhMegaphone as Megaphone,
  PhChat as MessageSquare,
  PhNewspaper as Newspaper,
  PhNotebook as Notebook,
  PhPackage as Package,
  PhPalette as Palette,
  PhPencilLine as PenLine,
  PhPresentationChart as Presentation,
  PhRocket as Rocket,
  PhMagnifyingGlass as Search,
  PhGearSix as Settings,
  PhShield as Shield,
  PhSparkle as Sparkles,
  PhStar as Star,
  PhTable as Table,
  PhTerminal as Terminal,
  PhUsers as Users,
  PhVideoCamera as Video,
  PhWrench as Wrench,
  PhLightning as Zap,
} from "@phosphor-icons/vue";
import type { CatalogIconName } from "@vynel/contracts/marketplace/catalog-icons";

export const CATALOG_ICONS: Record<CatalogIconName, Component> = {
  "book-open": BookOpen,
  bookmark: Bookmark,
  bot: Bot,
  briefcase: Briefcase,
  calendar: Calendar,
  "chart-bar": ChartBar,
  "chart-pie": ChartPie,
  "circle-check": CircleCheck,
  clipboard: Clipboard,
  clock: Clock,
  cloud: Cloud,
  code: Code,
  database: Database,
  "file-text": FileText,
  film: Film,
  folder: Folder,
  globe: Globe,
  "graduation-cap": GraduationCap,
  image: Image,
  inbox: Inbox,
  key: Key,
  languages: Languages,
  "layout-template": LayoutTemplate,
  lightbulb: Lightbulb,
  link: Link,
  "list-checks": ListChecks,
  mail: Mail,
  map: MapIcon,
  megaphone: Megaphone,
  "message-square": MessageSquare,
  newspaper: Newspaper,
  notebook: Notebook,
  package: Package,
  palette: Palette,
  "pen-line": PenLine,
  presentation: Presentation,
  rocket: Rocket,
  search: Search,
  settings: Settings,
  shield: Shield,
  sparkles: Sparkles,
  star: Star,
  table: Table,
  terminal: Terminal,
  users: Users,
  video: Video,
  wrench: Wrench,
  zap: Zap,
};
