// The catalog's lucide components, mapped statically so the bundle only
// carries icons the shelf can actually use. Typed against the contracts
// allowlist (`CatalogIconName`) — adding or removing a name in ONE home
// without the other fails the compile here. An iconName outside the map
// (legacy hub rows) falls back to the item's monogram in the card.

import type { Component } from "vue";
import {
  BookOpen,
  Bookmark,
  Bot,
  Briefcase,
  Calendar,
  ChartBar,
  ChartPie,
  CircleCheck,
  Clipboard,
  Clock,
  Cloud,
  Code,
  Database,
  FileText,
  Film,
  Folder,
  Globe,
  GraduationCap,
  Image,
  Inbox,
  Key,
  Languages,
  LayoutTemplate,
  Lightbulb,
  Link,
  ListChecks,
  Mail,
  Map as MapIcon,
  Megaphone,
  MessageSquare,
  Newspaper,
  Notebook,
  Package,
  Palette,
  PenLine,
  Presentation,
  Rocket,
  Search,
  Settings,
  Shield,
  Sparkles,
  Star,
  Table,
  Terminal,
  Users,
  Video,
  Wrench,
  Zap,
} from "lucide-vue-next";
import type { CatalogIconName } from "@vynel/contracts/marketplace/catalog-icons";

export const CATALOG_ICONS: Record<CatalogIconName, Component> = {
  "book-open": BookOpen,
  bookmark: Bookmark,
  bot: Bot,
  briefcase: Briefcase,
  calendar: Calendar,
  "chart-bar": ChartBar,
  "chart-pie": ChartPie,
  "circle-check": CircleCheck,
  clipboard: Clipboard,
  clock: Clock,
  cloud: Cloud,
  code: Code,
  database: Database,
  "file-text": FileText,
  film: Film,
  folder: Folder,
  globe: Globe,
  "graduation-cap": GraduationCap,
  image: Image,
  inbox: Inbox,
  key: Key,
  languages: Languages,
  "layout-template": LayoutTemplate,
  lightbulb: Lightbulb,
  link: Link,
  "list-checks": ListChecks,
  mail: Mail,
  map: MapIcon,
  megaphone: Megaphone,
  "message-square": MessageSquare,
  newspaper: Newspaper,
  notebook: Notebook,
  package: Package,
  palette: Palette,
  "pen-line": PenLine,
  presentation: Presentation,
  rocket: Rocket,
  search: Search,
  settings: Settings,
  shield: Shield,
  sparkles: Sparkles,
  star: Star,
  table: Table,
  terminal: Terminal,
  users: Users,
  video: Video,
  wrench: Wrench,
  zap: Zap,
};
