// Emits the full tool-catalog snapshot into `@vynel/contracts` — the static
// twin of `buildSessionToolCatalog()` for the surfaces that can't run the
// runtime assembly: the cloud-admin portal's matrix and the hub's
// operator-defaults validation. Runs AFTER `generate-mcp-tools.ts` in
// `pnpm api:generate` (the catalog derives from the generated registry).
//
// Committed + drift-guarded by `check-tool-catalog-parity.ts` in the gate,
// so the snapshot can never disagree with what the engine composes.

import { mkdirSync } from "node:fs";
import { writeIfChanged } from "./write-if-changed.js";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { buildSessionToolCatalog } from "@vynel/local-api/tool-catalog";
import { desktopFeatureDescriptor } from "@vynel/desktop-control";

const repoRoot = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "..",
  "..",
  "..",
);
const outPath = path.join(
  repoRoot,
  "packages",
  "contracts",
  "src",
  "generated",
  "tool-catalog-snapshot.ts",
);

// Codepoint comparison, NOT localeCompare — ICU collation varies by host
// locale and would flap the parity guard across machines.
function byCodepoint(a: string, b: string): number {
  return a < b ? -1 : a > b ? 1 : 0;
}

const catalog = [
  ...buildSessionToolCatalog({
    desktopToolNames: desktopFeatureDescriptor.toolNames ?? [],
  }),
].sort(
  (a, b) =>
    byCodepoint(a.serverName, b.serverName) ||
    byCodepoint(a.toolName, b.toolName),
);

const entries = catalog
  .map((entry) => `  ${JSON.stringify(entry)},`)
  .join("\n");

const file = `// GENERATED by scripts/src/generators/generate-tool-catalog.ts — do not edit.
// Run \`pnpm api:generate\` after any change to routes' x-mcp annotations,
// descriptor inventories, or the session tool catalog's surface maps.

import type { ToolCatalogEntry } from '../tool-policy/catalog.js'

/** Every tool the product composes, with its declared defaults — sorted by
 *  (serverName, toolName). ${catalog.length} entries. */
export const TOOL_CATALOG_SNAPSHOT: readonly ToolCatalogEntry[] = [
${entries}
]
`;

mkdirSync(path.dirname(outPath), { recursive: true });
writeIfChanged(outPath, file);
// eslint-disable-next-line no-console
console.log(
  `[tool-catalog:generate] wrote ${path.relative(repoRoot, outPath)} (${catalog.length} entries)`,
);
