// Chad's real shipped work, per product (2026-08-28) — pasted out of each
// project's own Claude Code session and kept here so the film kit arrives
// loaded instead of asking him to paste six lists into six boxes.
//
// SHIPPED WORK ONLY. Every source list also carried honest status notes —
// what is half-built, switched off, or insecure — and those are deliberately
// absent: these lines are SPOKEN in a video that gives the software away, and
// "accounts can be created and deleted without logging in" is not a sentence
// that belongs in one. The full lists live in Chad's own notes; this file is
// the promo cut.

export const DEMO_UPDATES_SEED: Readonly<Record<string, readonly string[]>> = {
  mintbird: [
    "the drag-and-drop page editor is in, with sections, rows and columns",
    "galleries, icons, dividers, spacers and containers all shipped",
    "testimonials, the FAQ accordion, star ratings and badges are in",
    "countdown timers, tabs, progress bars and navbars are done",
    "the announcement bar, social icons and lead forms are in",
    "you can start any page from the ready-made template library",
    "pages publish live to your own domain",
    "sales, upsell, downsell, signup and confirmation pages are built",
    "order forms and local-business pages are done",
    "Instant Pages shipped: lead steps, bridge pages and split tests",
    "PopLinks short links with tracking and rotation are in",
    "physical, digital and event products all sell",
    "product variants, options and bulk pricing are done",
    "subscriptions, payment plans and recurring billing are live",
    "order bumps, one-click upsells and downsells are in",
    "coupons, discounts and dime sales are working",
    "full sales funnels with steps and split tests are built",
    "refunds are handled through the payment gateways",
    "the dashboard shows sales, leads and live activity maps",
    "per-page and per-funnel stats with source tracking are in",
    "leads export to a spreadsheet",
    "the enterprise dashboard covers staff assignment and failed-sale tracking",
    "Stripe, NMI, EasyPayDirect and Razorpay are all taking payments",
    "ActiveCampaign, AWeber, GetResponse and Mailchimp are connected",
    "custom domains add, verify and manage themselves",
    "enterprise login with your own branding and staff accounts is in",
    "many client sub-accounts run under one login",
  ],
  "video-geyser": [
    "the drag-and-drop editor has been rebuilt and is stable",
    "anything nests inside anything now",
    "the layers panel, with rename, hide and reorder, is in",
    "desktop, tablet and mobile style separately",
    "autosave and auto-republish are live",
    "version history with restore is in",
    "saved blocks and section libraries are in",
    "one colour theme drives a whole page",
    "scroll animations and hover styles are done",
    "sales, upsell, downsell and opt-in pages are done",
    "pages publish to your domain with clean addresses",
    "someone-just-bought notifications are live",
    "digital, physical and event products are all supported",
    "subscriptions, instalments and trials are done",
    "one-page and multi-step checkout both work",
    "one-click upsells are in",
    "coupons and automatic discounts are done",
    "Stripe is fully wired, including merchant onboarding",
    "recurring billing and invoices are done",
    "chasing failed payments is in",
    "split testing works, with traffic-split control",
    "ShipStation is fully wired",
    "traffic-source attribution reaches the sale",
    "short tracked links are in",
    "the world map of clicks is in",
    "Meta Pixel and server-side conversions are fully wired",
    "sixteen autoresponders are wired, including Mailchimp and ActiveCampaign",
    "AI writes a whole page, streamed section by section",
    "one sentence now generates a full template",
    "the funnel planner builds the funnel it plans",
    "products and order bumps get created automatically",
    "AI runs on Claude, OpenAI and Kimi",
    "affiliate programs with commission tiers are done",
    "batch payouts work, via PayPal, Wise or Venmo",
    "ad campaigns with budgets and spend alerts are in",
  ],
  quizforma: [
    "the quiz builder is finished, with seventeen question types",
    "the welcome screen and four end screens are in",
    "branching, disqualifying answers, points and score bands are done",
    "the designer lets you style any element on the page",
    "fourteen ready-made templates shipped",
    "own-domain publishing with automatic SSL is live",
    "the public player is fast, mobile-friendly and resumable",
    "entries filter, search and export to a spreadsheet",
    "dashboard reporting covers totals, trends and a lead map",
    "per-question statistics show who answered what",
    "Global Control is connected for tags, contacts and pipeline routing",
    "AI writes your questions on Claude or OpenAI",
    "share codes, quiz import and cloning all work",
    "Pexels, Unsplash and geo lookup are wired in",
  ],
  "nicely-community": [
    "drag-and-drop page editing is live",
    "thirty blocks shipped: text, buttons, images, video and forms",
    "two hundred and forty-four ready-made section designs are loaded",
    "phone and desktop layouts are now separate",
    "pages publish themselves after editing",
    "version history with restore is working",
    "importing a page from a website works",
    "physical, digital and event products are in",
    "payment plans and instalments are live",
    "one-step and multi-step order forms shipped",
    "Stripe is fully wired",
    "sellers can connect their own Stripe account",
    "one-click upsells shipped",
    "checkout can be embedded on outside sites",
    "multi-step funnels are built",
    "split testing is working",
    "the dashboard with charts and map is in",
    "failed-payment recovery lists are working",
    "short links with click tracking shipped",
    "AWeber, Mailchimp, GetResponse and ActiveCampaign are connected",
    "pages can now be written from one sentence",
    "plans can now be turned into funnels",
    "automatic quality checking and self-repair is in",
    "affiliate programs are live",
    "batch commission payouts shipped",
    "the client portal is live",
  ],
  letterman: [
    "the drag-and-drop newsletter editor is finished, with twenty-eight block types",
    "the article writer is in, with a search-engine summary panel",
    "scheduling and sending to subscribers works",
    "sends can be watched live and paused, cancelled or retried",
    "Today's Cue shows everything going out that day",
    "RSS feeds import and convert into articles",
    "every publication gets a full public site on its own domain",
    "the back-issue archive and latest-issue pages are live",
    "the signup page builder is finished",
    "the welcome email and multi-step welcome series are in",
    "reader comments work, with moderation, replies and reactions",
    "price lists for ad spots and sponsorships are in",
    "the ad booking calendar shows what's still free",
    "ad slots inside the emailed issue are live",
    "Stripe is wired up for card payments and subscriptions",
    "the revenue planner projects income from subscribers and pricing",
    "advertisers can order from the site without asking the publisher",
    "the business directory is live, with categories and profiles",
    "community events listings are in",
    "the business owner portal handles listing, photos, schedule and billing",
    "newsletter delivery and engagement reporting is in",
    "AI writes whole articles from a keyword or a link",
    "AI drafts newsletter blocks and headlines",
    "ElevenLabs reads each issue aloud as an audio recap",
    "product review landing pages shipped this week",
    "cross-promotion partnerships between newsletters are in",
  ],
  "global-control": [
    "the drag-and-drop page editor is built and stable",
    "keyboard shortcuts are wired up across the editor",
    "desktop, tablet and mobile layouts are fully supported",
    "twelve page-wide motion styles have shipped",
    "section, row and full-page template libraries are in",
    "autosave and auto-publish-on-pause are both running",
    "animated headlines with rotating words and typewriter effects shipped",
    "image galleries — grid, carousel, before and after — have shipped",
    "popups with exit-intent and click triggers are built",
    "physical, digital and event products are all selling",
    "subscriptions, trials and recurring billing are working",
    "single-step and multi-step checkout are both done",
    "Stripe, NMI, EPD and Razorpay are taking payments",
    "one-click repeat purchases with saved cards are done",
    "refunds, including partial refunds, are complete",
    "multi-step sales funnels are fully built",
    "split testing on pages, steps and bumps is working",
    "the sales dashboard with charts and map is live",
    "the live incoming lead feed is running",
    "real-time visitor maps per link are live",
    "over thirty autoresponders are wired up",
    "ShipStation fulfilment is live for single and multi-item orders",
    "full page generation from a written brief is built",
    "automatic quality checks on generated pages are running",
    "AI logo generation and editing have shipped",
    "the funnel blueprint wizard is complete",
    "OpenAI, Anthropic Claude and Moonshot Kimi are all powering this",
    "the partner portal — dashboard, sales, leads and pages — is done",
    "geo-targeting links by country is working",
    "live social-proof popups on pages are working",
  ],
  "course-sprout": [
    "the course library is live, with search, categories and grid or list view",
    "chapters can be dragged into order and published one at a time",
    "free-preview lessons show content before someone buys",
    "the resource library is live — downloads attach to any lesson",
    "a central video library landed, with tags, thumbnails and search",
    "playback works for Vimeo, YouTube, Gumlet and Adilo",
    "drip-feed shipped: chapters release gradually over a set number of days",
    "course export and import via share code is working",
    "memberships are live and bundle many courses together",
    "bulk member import from a spreadsheet is working",
    "locked courses now show as teasers to encourage upgrades",
    "collections shipped — they bundle products into their own branded portal",
    "card checkout through Stripe is live",
    "access is granted the moment a payment succeeds",
    "guest checkout works by email; buyers don't need an account first",
    "coupon codes are built, with expiry and stock limits",
    "the order form editor is live, with template and colour palette pickers",
    "checkout supports nine currencies",
    "the dashboard is live with revenue, leads, active members and goals",
    "a live world map shows where members are signing in from",
    "phone push notifications are live through Firebase",
    "Instant Lesson builds a lesson from a video transcript",
    "points are awarded for watching, downloads, comments and likes",
    "the leaderboard, badge wall and member levels are in",
    "the community feed is live per course, with topics and pinned posts",
    "private member-to-member messaging is live",
    "a course events calendar is in, with automatic reminders",
    "the moderation inbox covers lesson and community comments in one place",
  ],
};
